SET XACT_ABORT ON
--SET XACT_ABORT OFF
BEGIN TRY
BEGIN TRANSACTION
--	INSERT INTO [SQL-XXID].[new].[dbo].MANUFACTURERS (M_NAME) VALUES ('Какой-то производитель') 

	INSERT INTO [SQLBOOCK].[new_gal].[dbo].MANUFACTURERS (M_NAME) VALUES ('Какой-то производитель') 
	INSERT INTO [SQLBOOCK].[new_gal].[dbo].MANUFACTURERS (M_NAME) VALUES ('Какой-то производитель2') 

	COMMIT
END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0 ROLLBACK
END CATCH

-- exec [S$LINKED_TEST] '111'
/*
DECLARE @XACT_ABORT VARCHAR(3) = 'OFF';
IF ( (16384 & @@OPTIONS) = 16384 ) SET @XACT_ABORT = 'ON';
SELECT @XACT_ABORT AS XACT_ABORT;
*/

/*
SET XACT_ABORT ON
BEGIN TRY
BEGIN DISTRIBUTED TRANSACTION
--BEGIN TRANSACTION
--	INSERT INTO [SQL-XXID].[new].[dbo].MANUFACTURERS (M_NAME) VALUES ('Какой-то производитель') 

	INSERT INTO [SQLBOOCK].[new_gal].[dbo].MANUFACTURERS (M_NAME) VALUES ('Какой-то производитель') 
	INSERT INTO [SQLBOOCK].[new_gal].[dbo].MANUFACTURERS (M_NAME) VALUES ('Какой-то производитель2') 

	COMMIT
END TRY
BEGIN CATCH
    Select 'фигня'
	IF @@TRANCOUNT > 0 ROLLBACK
END CATCH
*/