SELECT 
P.P_NAME,
Max(JOURNAL.J_ID) AS [J_ID], Max(JOURNAL.J_DATE) AS [J_DATE], JOURNAL.A_ID, Sum(JOURNAL.J_QTY) AS [J_QTY], Sum(JOURNAL.J_QTYU) AS [J_QTYU], Min(JOURNAL.J_RES) AS [J_RES], Min(JOURNAL.D_ID) AS [D_ID], Min(JOURNAL.J_TYPE) AS [J_TYPE]
FROM JOURNAL
LEFT JOIN ARTICLES A ON  A.A_ID = JOURNAL.A_ID
LEFT JOIN PRODUCTS P ON  P.P_NREC = A.P_NREC
GROUP BY JOURNAL.A_ID, P.P_NAME
HAVING (((Sum(JOURNAL.J_QTY))>0))
